### PR TITLE
Create more things

### PR DESCRIPTION
**Pull request by littlewhitecloud**
- [x] add ```.strip()``` for get cmd
- [x] add scrollbar for text widget
- [x] support key up and down
~~add a theme for terminal widget (dark and light)~~
- [x] record & read history command
~~and more...~~

### CODE REVIEW

**Comment by Moosems** [comment]
I think we should keep the scrollbars.

**Comment by Moosems** [comment]
Dark and light themes probably isn't the way to go but instead I'd allow a custom tkinter theme as those are much better for everyone then just a dark or light mode. I keep my applications not stuck in sv_ttk and it'd be a drawback if I was forced to use it.

**Comment by littlewhitecloud** [comment]
> Dark and light themes probably isn't the way to go but instead I'd allow a custom tkinter theme as those are much better for everyone then just a dark or light mode. I keep my applications not stuck in sv_ttk and it'd be a drawback if I was forced to use it.

image
I mean the ```Text``` widget is black, should we make a light one?

**Comment by littlewhitecloud** [comment]
nvm, just do it in other pr.

**Comment by Moosems** [comment]
What is the point of the auto hiding scroll bars? Will they reappear ever?

**Pull request merged**
